### ISSUE TITLE
Why use port 9440?

### ISSUE THREAD

**Issue by xiedeyantu** [PostHog/HouseWatch#5]
Why not use port 8123 or 9000?

housewatch-app-1     | Failed to connect to localhost:9440
housewatch-app-1     | Traceback (most recent call last):
housewatch-app-1     |   File "/usr/local/lib/python3.10/site-packages/clickhouse_driver/connection.py", line 342, in connect
housewatch-app-1     |     return self._init_connection(host, port)
housewatch-app-1     |   File "/usr/local/lib/python3.10/site-packages/clickhouse_driver/connection.py", line 306, in _init_connection
housewatch-app-1     |     self.socket = self._create_socket(host, port)
housewatch-app-1     |   File "/usr/local/lib/python3.10/site-packages/clickhouse_driver/connection.py", line 278, in _create_socket
housewatch-app-1     |     raise err
housewatch-app-1     |   File "/usr/local/lib/python3.10/site-packages/clickhouse_driver/connection.py", line 269, in _create_socket
housewatch-app-1     |     sock.connect(sa)
housewatch-app-1     |   File "/usr/local/lib/python3.10/ssl.py", line 1375, in connect
housewatch-app-1     |     self._real_connect(addr, False)
housewatch-app-1     |   File "/usr/local/lib/python3.10/ssl.py", line 1362, in _real_connect

**Comment by yakkomajuri** [comment]
Hey @xiedeyantu! 

I just corrected a mistake that defaulted to `CLICKHOUSE_SECURE=True` and ClickHouse uses port 9440 by default for TLS connections, which the client relies on. Updating the repo or setting `CLICKHOUSE_SECURE=False` should fix things for you!

**Comment by aaronvg** [comment]
minor nit: it's actually `CLICKHOUSE_SECURE=false` (lowercase)
