### ISSUE TITLE
Frontend always request to localhost:8000

### ISSUE THREAD

**Issue by huwngnosleep** [PostHog/HouseWatch#8]
I found all request from frontend always come to localhost:8000, which is not true if you host the webserver on server then woking on local machine browser, should I make an improvement by adding server host as an env?

![image](https://github.com/PostHog/HouseWatch/assets/73866831/a86b3e02-a4a6-4072-ba78-3d358920abfe)

![image](https://github.com/PostHog/HouseWatch/assets/73866831/168fd7e9-6191-4c8b-a526-b50bdd73f2fa)

**Comment by yakkomajuri** [comment]
Happy to take a PR to improve this - we certainly shouldn't hardcode it and should probably set up a `proxy` in `package.json`.

But unsure why you'd run the frontend and backend separately?

**Comment by huwngnosleep** [comment]
I just set up this repo in server then access from local browser, like many other websites, wondering why your situation need to run frontend and backend in the same local machine? 
Our situation need to provide access to other people in the team, so it can not be set up in local

**Comment by hadouvex** [comment]
@yakkomajuri +1, running compose on a virtual machine with public ip adress since we want to provide shared access to the housewatch. Hardcoded localhost in url makes it impossible, at least i haven't find any workaround by this moment

**Comment by yakkomajuri** [comment]
Hey @hadouvex @huwngnosleep I'm away for a little period now, but feel free to submit a PR with a solution that works for you.

You can tag me and @fuziontech on it
